name: Linting
on: workflow_dispatch
permissions: 
  contents: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: dependencies
        run: npm ci
      - name: oxlint
        run: | 
            npm run lint > lint-info.md
      - name: Commit-changes
        run: |
          git config --global user.name 'repenaattori''
          git config --global user.email 'reimarii@oamk.fi'
          git add .
          git commit -m 'Linting report'
            
